-- DAF Academy V2 - Supabase schema
-- Run this file once in Supabase > SQL Editor.

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_read boolean not null default false,
  best_score integer not null default 0 check (best_score between 0 and 100),
  attempts integer not null default 0,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, module_slug)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  score integer not null check (score between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  xp integer not null default 0,
  streak integer not null default 0,
  last_active_date date
);

alter table public.user_progress enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.user_stats enable row level security;

drop policy if exists "Users read own progress" on public.user_progress;
drop policy if exists "Users insert own progress" on public.user_progress;
drop policy if exists "Users update own progress" on public.user_progress;
drop policy if exists "Users read own attempts" on public.quiz_attempts;
drop policy if exists "Users insert own attempts" on public.quiz_attempts;
drop policy if exists "Users read own stats" on public.user_stats;
drop policy if exists "Users insert own stats" on public.user_stats;
drop policy if exists "Users update own stats" on public.user_stats;

create policy "Users read own progress" on public.user_progress for select using (auth.uid() = user_id);
create policy "Users insert own progress" on public.user_progress for insert with check (auth.uid() = user_id);
create policy "Users update own progress" on public.user_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users read own attempts" on public.quiz_attempts for select using (auth.uid() = user_id);
create policy "Users insert own attempts" on public.quiz_attempts for insert with check (auth.uid() = user_id);

create policy "Users read own stats" on public.user_stats for select using (auth.uid() = user_id);
create policy "Users insert own stats" on public.user_stats for insert with check (auth.uid() = user_id);
create policy "Users update own stats" on public.user_stats for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
